version: "3.9"
services:
    web:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - db   
    db:
        image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
        environment:
            SA_PASSWORD: "PASSWORD1!"
            ACCEPT_EULA: "Y"
            MSSQL_PID: Express
        ports:
            - "1433:1433"     